### ISSUE TITLE
Website link not working for literary research guide

### ISSUE THREAD

**Issue by scottvieira** [mlaa/literary-research-guide#1]
Is the link for the mlalrg.org site supposed to be working?  Or is the site under construction?

**Comment by tlewek** [comment]
Hi, Scott,

We discontinued the 6th ed. site in December; mlalrg.org should now redirect to a static page that explains this and invites individuals to use the code in this repository.

Please let me know if you have any additional questions or concerns.

Thanks,
Tom

**Comment by scottvieira** [comment]
@tlewek Thanks.
